from __future__ import annotations

from dataclasses import dataclass, asdict, field
from typing import Any, Dict, List, Optional, Set

# ---------------------------------------------------------------------------
# Normalization result for a field value
# ---------------------------------------------------------------------------

@dataclass
class NormalizedValue:
    """Result of normalizing a text fragment for a given field."""
    field_name: str
    raw_text: str
    canonical_value: str
    match_type: str                      # exact / alias / normalized / semantic
    confidence: float = 1.0
    protected: bool = False
    evidence: str = ""
    accepted_values: List[str] = field(default_factory=list)


@dataclass(frozen=True)
class AssetFact:
    """One row in the internal restricted fact pool.

    The default field names match the paper example, but `extra` lets the same
    engine work as a generic template: policy fields can point at any JSON key.
    """

    id: str
    system_name: str
    business_domain: str
    environment: str
    function_category: str
    component_version: str
    risk_status: str
    disposition_status: str
    remote_entry: str = ""
    extra: Dict[str, Any] = field(default_factory=dict)

    def get(self, field_name: str) -> str:
        if hasattr(self, field_name):
            return str(getattr(self, field_name) or "")
        return str(self.extra.get(field_name, "") or "")

    def display_name(self, display_field: str = "system_name") -> str:
        value = self.get(display_field)
        if value:
            return value
        for field_name in ("system_name", "name", "title", "display_name", "id"):
            value = self.get(field_name)
            if value:
                return value
        return self.id

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "AssetFact":
        known = {
            "id",
            "system_name",
            "business_domain",
            "environment",
            "function_category",
            "component_version",
            "risk_status",
            "disposition_status",
            "remote_entry",
        }
        kwargs = {k: data.get(k, "") for k in known if k != "extra"}
        if not kwargs.get("system_name"):
            kwargs["system_name"] = str(
                data.get("name") or data.get("title") or data.get("display_name") or data.get("id") or ""
            )
        extra = {k: v for k, v in data.items() if k not in known}
        return cls(extra=extra, **kwargs)


# ---------------------------------------------------------------------------
# Default match-type weights used when policy does not provide them.
# ---------------------------------------------------------------------------

DEFAULT_MATCH_TYPE_WEIGHTS: Dict[str, float] = {
    "exact": 1.00,
    "alias": 0.90,
    "semantic": 0.80,
    "partial": 0.65,
    "inferred": 0.70,
    "ambiguous": 0.45,
}


# ---------------------------------------------------------------------------
# Semantic alias structures (offline-generated by LLM).
# ---------------------------------------------------------------------------

@dataclass
class SemanticFieldAlias:
    """Rich semantic alias info for one canonical field value."""
    components: List[str] = field(default_factory=list)
    aliases: List[str] = field(default_factory=list)
    partial_clues: List[str] = field(default_factory=list)
    possible_inferences: List[Dict[str, str]] = field(default_factory=list)
    partial_match_policy: str = "any_component_or_alias"


# Semantic aliases map: field_name -> canonical_value -> SemanticFieldAlias
SemanticAliasMap = Dict[str, Dict[str, SemanticFieldAlias]]


@dataclass
class CandidateValue:
    """A candidate field value recalled by SemanticIndex."""
    field_name: str
    canonical_value: str
    score: float
    source: str = "hybrid_sparse"
    matched_terms: List[str] = field(default_factory=list)
    score_breakdown: Dict[str, float] = field(default_factory=dict)


# ---------------------------------------------------------------------------
# v2.3 — Candidate snapshot and restoration decision
# ---------------------------------------------------------------------------

@dataclass
class CandidateSnapshot:
    """Snapshot of candidate sets before and after output anchors are applied."""
    input_candidates: List[AssetFact] = field(default_factory=list)
    final_candidates: List[AssetFact] = field(default_factory=list)
    input_anchors: List[Anchor] = field(default_factory=list)
    output_anchors: List[Anchor] = field(default_factory=list)
    contributing_output_anchors: List[Anchor] = field(default_factory=list)
    information_gain_bits: float = 0.0


@dataclass
class RestorationDecision:
    """Result of the CFA restoration shape check."""
    detected: bool = False
    trigger_type: str = ""             # direct_protected_disclosure / indirect_asset_restoration /
                                       # indirect_protected_value_restoration / inconsistent_evidence
    restored_fields: List[str] = field(default_factory=list)
    reason: str = ""


# ---------------------------------------------------------------------------
# v2.7 — Audit record for intermediate results
# ---------------------------------------------------------------------------

@dataclass
class AuditRecord:
    """Complete intermediate results for one CFA analysis pass.

    Records all key decision points so the audit trail is self-contained
    and reproducible.  This replaces implicit scattered logging with an
    explicit structured record.
    """
    input_anchors: List[Dict[str, Any]] = field(default_factory=list)
    output_anchors: List[Dict[str, Any]] = field(default_factory=list)
    input_candidate_ids: List[str] = field(default_factory=list)
    final_candidate_ids: List[str] = field(default_factory=list)
    input_candidate_count: int = 0
    final_candidate_count: int = 0
    restored_fact_ids: List[str] = field(default_factory=list)
    restored_fields: List[str] = field(default_factory=list)
    information_gain_bits: float = 0.0
    trigger_type: str = ""
    decision_reason: str = ""


# ---------------------------------------------------------------------------
# FieldPolicy (extended with semantic aliases and LLM extraction config).
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class FieldPolicy:
    # ---- 核心字段分类 ----
    protected_fields: List[str]
    identifier_fields: List[str]
    quasi_identifier_fields: List[str]
    field_order: List[str]
    field_labels: Dict[str, str]
    field_weights: Dict[str, float]
    field_aliases: Dict[str, Dict[str, List[str]]]
    public_rules: List[Dict[str, Any]]

    # ---- 唯一性阈值 ----
    uniqueness_k: int = 1
    display_field: str = "system_name"

    # ---- 安全改写配置 ----
    safe_replacements: Dict[str, str] = field(default_factory=dict)
    safe_hint: str = ""

    # ---- 显式敏感字段池（额外补充，可与 protected/id/display 自动合并） ----
    sensitive_fields: List[str] = field(default_factory=list)

    # ---- v2.3 间接还原检测配置 ----
    indirect_restoration_enabled: bool = True
    min_candidate_reduction: int = 1
    min_information_gain_bits: float = 0.5
    protected_value_k: int = 1
    min_protected_entropy_drop_bits: float = 0.5

    # ---- LLM 相关配置 ----
    semantic_aliases: Dict[str, Dict[str, Dict[str, Any]]] = field(default_factory=dict)
    match_type_weights: Dict[str, float] = field(default_factory=dict)
    llm_extraction_fields: List[str] = field(default_factory=list)
    llm_confidence_threshold: float = 0.4
    llm_max_accepted_values: int = 30

    # ---- v2.7: Schema-generic slot-fill detection ----
    # When enabled, the engine looks for I/O slot-restoration patterns
    # (user asks a slot question, model supplies the value).  The terms
    # below define what constitutes a slot query / attribute / connector
    # in the target domain language.
    slot_detection_enabled: bool = False
    slot_query_terms: List[str] = field(default_factory=list)
    slot_attribute_terms: List[str] = field(default_factory=list)
    slot_connector_terms: List[str] = field(default_factory=list)
    slot_output_value_pattern: str = ""
    slot_value_unit_hints: Dict[str, str] = field(default_factory=dict)

    # ---- v2.7: Schema-generic confirmation detection ----
    # When enabled, the engine checks whether the model confirms/echoes
    # protected facts already supplied by the user input.
    confirmation_detection_enabled: bool = False
    confirmation_terms: List[str] = field(default_factory=list)
    refusal_terms: List[str] = field(default_factory=list)
    common_text_fragments: List[str] = field(default_factory=list)

    # ---- v2.7: Schema-generic field sensitivity level ----
    # Per-field sensitivity: public / protected.  If empty, all
    # protected_fields are treated as protected.  identifier_fields
    # are treated as public by default.
    field_sensitivity: Dict[str, str] = field(default_factory=dict)  # field_name -> "public" | "protected"

    # ---- v2.7: Field data type hints for value normalization ----
    # e.g. {"loan_amount": "amount", "interest_rate": "rate", "score": "number"}
    # Used by the extractor to determine how to parse raw text into
    # canonical values (amount normalization, rate parsing, etc.).
    field_data_types: Dict[str, str] = field(default_factory=dict)

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "FieldPolicy":
        semantic_raw = data.get("semantic_aliases", {})
        semantic_aliases: Dict[str, Dict[str, Dict[str, Any]]] = {}
        if isinstance(semantic_raw, dict):
            for field_name, value_map in semantic_raw.items():
                if isinstance(value_map, dict):
                    semantic_aliases[str(field_name)] = {
                        str(canonical): dict(info) if isinstance(info, dict) else {}
                        for canonical, info in value_map.items()
                    }

        return cls(
            protected_fields=list(data.get("protected_fields", [])),
            identifier_fields=list(data.get("identifier_fields", [])),
            quasi_identifier_fields=list(data.get("quasi_identifier_fields", [])),
            field_order=list(data.get("field_order", [])),
            field_labels=dict(data.get("field_labels", {})),
            field_weights=dict(data.get("field_weights", {})),
            field_aliases=dict(data.get("field_aliases", {})),
            public_rules=list(data.get("public_rules", [])),
            uniqueness_k=int(data.get("uniqueness_k", 1)),
            display_field=str(data.get("display_field", "system_name")),
            safe_replacements=dict(data.get("safe_replacements", {})),
            safe_hint=str(data.get("safe_hint", "")),
            sensitive_fields=list(data.get("sensitive_fields", [])),
            # v2.3
            indirect_restoration_enabled=bool(data.get("indirect_restoration_enabled", True)),
            min_candidate_reduction=int(data.get("min_candidate_reduction", 1)),
            min_information_gain_bits=float(data.get("min_information_gain_bits", 0.5)),
            protected_value_k=int(data.get("protected_value_k", 1)),
            min_protected_entropy_drop_bits=float(data.get("min_protected_entropy_drop_bits", 0.5)),
            # LLM
            semantic_aliases=semantic_aliases,
            match_type_weights=dict(data.get("match_type_weights", {})),
            llm_extraction_fields=list(data.get("llm_extraction_fields", [])),
            llm_confidence_threshold=float(data.get("llm_confidence_threshold", 0.4)),
            llm_max_accepted_values=int(data.get("llm_max_accepted_values", 30)),
            # v2.7: Schema-generic slot detection
            slot_detection_enabled=bool(data.get("slot_detection_enabled", False)),
            slot_query_terms=list(data.get("slot_query_terms", [])),
            slot_attribute_terms=list(data.get("slot_attribute_terms", [])),
            slot_connector_terms=list(data.get("slot_connector_terms", [])),
            slot_output_value_pattern=str(data.get("slot_output_value_pattern", "")),
            slot_value_unit_hints=dict(data.get("slot_value_unit_hints", {})),
            # v2.7: Schema-generic confirmation detection
            confirmation_detection_enabled=bool(data.get("confirmation_detection_enabled", False)),
            confirmation_terms=list(data.get("confirmation_terms", [])),
            refusal_terms=list(data.get("refusal_terms", [])),
            common_text_fragments=list(data.get("common_text_fragments", [])),
            # v2.7: Field sensitivity and data types
            field_sensitivity=dict(data.get("field_sensitivity", {})),
            field_data_types=dict(data.get("field_data_types", {})),
        )

    def label(self, field_name: str) -> str:
        return self.field_labels.get(field_name, field_name)

    def weight(self, field_name: str) -> float:
        return float(self.field_weights.get(field_name, 0.05))

    def match_type_weight(self, match_type: str) -> float:
        """Get the weight multiplier for a given match type."""
        if self.match_type_weights:
            return float(self.match_type_weights.get(match_type, 1.0))
        return DEFAULT_MATCH_TYPE_WEIGHTS.get(match_type, 1.0)

    def get_semantic_aliases(self, field_name: str) -> Dict[str, SemanticFieldAlias]:
        """Return parsed semantic aliases for a field."""
        raw = self.semantic_aliases.get(field_name, {})
        result: Dict[str, SemanticFieldAlias] = {}
        for canonical, info in raw.items():
            result[canonical] = SemanticFieldAlias(
                components=[str(c) for c in info.get("components", [])],
                aliases=[str(a) for a in info.get("aliases", [])],
                partial_clues=[str(p) for p in info.get("partial_clues", [])],
                possible_inferences=[
                    dict(i) for i in info.get("possible_inferences", [])
                ],
                partial_match_policy=str(
                    info.get("partial_match_policy", "any_component_or_alias")
                ),
            )
        return result

    def is_field_protected(self, field_name: str) -> bool:
        """Check whether a field is protected based on field_sensitivity or defaults."""
        if self.field_sensitivity:
            sensitivity = self.field_sensitivity.get(field_name, "")
            if sensitivity == "protected":
                return True
            if sensitivity == "public":
                return False
        # Fallback: use protected_fields list
        return field_name in set(self.protected_fields)

    def field_slot_protected_fields(self) -> List[str]:
        """Return protected fields that can serve as slot-fill targets.

        These are protected fields that are NOT identifier fields
        (identifier fields are the ones that name the entity, not the
        sensitive values being protected).  For healthcare this would be
        diagnosis/medication (not patient_name).  For finance this would
        be loan_amount/interest_rate (not company_name).
        """
        id_set = set(self.identifier_fields)
        return [f for f in self.protected_fields if f not in id_set]


# ---------------------------------------------------------------------------
# Anchor (extended with LLM semantic fields).
# ---------------------------------------------------------------------------

@dataclass
class Anchor:
    id: str
    field_name: str
    field_label: str
    text: str
    canonical_value: str
    start: int
    end: int
    anchor_type: str
    protected: bool
    inferred: bool = False
    evidence: str = ""
    source_anchor_id: Optional[str] = None
    source: str = "output"

    # -------- New: LLM semantic extraction fields --------
    match_type: str = "exact"
    confidence: float = 1.0
    llm_reason: str = ""
    accepted_values: List[str] = field(default_factory=list)

    # -------- v2.3: Anchor provenance tracking --------
    extractor_sources: List[str] = field(default_factory=list)
    merged_anchor_ids: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "field_name": self.field_name,
            "field_label": self.field_label,
            "text": self.text,
            "canonical_value": self.canonical_value,
            "start": self.start,
            "end": self.end,
            "anchor_type": self.anchor_type,
            "protected": self.protected,
            "source": self.source,
            "inferred": self.inferred,
            "evidence": self.evidence,
            "source_anchor_id": self.source_anchor_id,
            "match_type": self.match_type,
            "confidence": self.confidence,
            "llm_reason": self.llm_reason,
            "accepted_values": list(self.accepted_values),
            "extractor_sources": list(self.extractor_sources),
            "merged_anchor_ids": list(self.merged_anchor_ids),
        }

    def effective_canonical_value(self) -> str:
        """Return the best representative value for display."""
        if self.canonical_value:
            return self.canonical_value
        if self.accepted_values:
            if len(self.accepted_values) == 1:
                return self.accepted_values[0]
            return f"{{{len(self.accepted_values)}个候选}}"
        return ""

    def match_symbol(self) -> str:
        """Return the symbol to display in reduction chains."""
        if self.match_type in ("exact", "alias"):
            return "="
        return "≈"


# ---------------------------------------------------------------------------
# v2.5 — DisclosureClaim for multi-claim CFA detection
# ---------------------------------------------------------------------------

@dataclass
class DisclosureClaim:
    """One local disclosure claim split from the model output.

    Each claim independently participates in candidate binding, risk
    detection, and sanitization.  Claims are UNION-ed, not AND-ed.
    """
    claim_id: str
    text: str
    start: int
    end: int
    context_anchors: List[Anchor] = field(default_factory=list)
    local_output_anchors: List[Anchor] = field(default_factory=list)
    candidate_assets: List[AssetFact] = field(default_factory=list)
    candidate_asset_ids: List[str] = field(default_factory=list)


# ---------------------------------------------------------------------------
# ReductionStep, RiskFinding, AnalysisResult.
# ---------------------------------------------------------------------------

@dataclass
class ReductionStep:
    field_name: str
    field_label: str
    anchor_text: str
    canonical_value: str
    before_count: int
    after_count: int
    remaining_asset_ids: List[str]
    match_symbol: str = "="

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class RiskFinding:
    target_asset_id: str
    target_asset_name: str
    risk_level: str
    score: float
    reason: str
    restored_fact: str
    anchors: List[Anchor]
    reduction_chain: List[ReductionStep]
    minimal_combinations: List[List[str]]
    key_anchor_ids: List[str] = field(default_factory=list)
    key_anchor_summary: List[str] = field(default_factory=list)

    # -------- v2.3 extensions --------
    finding_type: str = "asset_restoration"
    target_asset_ids: List[str] = field(default_factory=list)
    restored_fields: List[str] = field(default_factory=list)
    input_candidate_count: int = 0
    final_candidate_count: int = 0
    information_gain_bits: float = 0.0

    def to_dict(self) -> Dict[str, Any]:
        data = asdict(self)
        data["anchors"] = [a.to_dict() for a in self.anchors]
        data["reduction_chain"] = [s.to_dict() for s in self.reduction_chain]
        return data


@dataclass
class AnalysisResult:
    raw_answer: str
    anchors: List[Anchor]
    findings: List[RiskFinding]
    x_replaced_answer: str
    safe_answer: str
    user_input: str = ""
    model_output: str = ""
    secondary_check_performed: bool = False
    secondary_safe_answer: str = ""
    secondary_findings: List[RiskFinding] = field(default_factory=list)

    # -------- v2.7: Audit trail for intermediate results --------
    audit: AuditRecord = field(default_factory=AuditRecord)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "user_input": self.user_input,
            "model_output": self.model_output or self.raw_answer,
            "raw_answer": self.raw_answer,
            "anchors": [a.to_dict() for a in self.anchors],
            "findings": [f.to_dict() for f in self.findings],
            "x_replaced_answer": self.x_replaced_answer,
            "safe_answer": self.safe_answer,
            "secondary_check_performed": self.secondary_check_performed,
            "secondary_safe_answer": self.secondary_safe_answer,
            "secondary_findings": [f.to_dict() for f in self.secondary_findings],
            # v2.7: Audit trail
            "audit": {
                "input_anchors": self.audit.input_anchors,
                "output_anchors": self.audit.output_anchors,
                "input_candidate_ids": self.audit.input_candidate_ids,
                "final_candidate_ids": self.audit.final_candidate_ids,
                "input_candidate_count": self.audit.input_candidate_count,
                "final_candidate_count": self.audit.final_candidate_count,
                "restored_fact_ids": self.audit.restored_fact_ids,
                "restored_fields": self.audit.restored_fields,
                "information_gain_bits": self.audit.information_gain_bits,
                "trigger_type": self.audit.trigger_type,
                "decision_reason": self.audit.decision_reason,
            },
        }